
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/usr/local/share/cmake-3.27/Modules/CMakeDetermineSystem.cmake:206 (message)"
      - "CMakeLists.txt:8 (project)"
    message: |
      The target system is: Emscripten - 1 - x86
      The host system is: Linux - 6.2.0-1016-azure - x86_64
...
