name: Close Pull Request

on:
  pull_request:
    types: [opened]
    branches: "main"
    paths:
    - "data/**"

jobs: 
  
  closePR:
    permissions:
      pull-requests: write 

    if: github.repository_owner == 'hjenryin'
    runs-on: ubuntu-latest
    steps:
    - uses: superbrothers/close-pull-request@v3
      with:
        # Optional. Post a issue comment just before closing a pull request.
        comment: "检测到PR中包含对data/**的改动，一般情况下是其他用户更新错了方向导致的，因此关闭此PR。请阅读https://github.com/hjenryin/BCJH-Metropolis/blob/main/assets/manuallyUpdate.md。如果有其他情况也请回复或联系我。"
